### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/good-modal#1]
- [ ] Disable scroll ([`no-scroll`](https://github.com/davidtheclark/no-scroll))
- [ ] DOM unmounting/mounting + transition support 
- [ ] Focus trap ([this lib](https://github.com/davidtheclark/focus-trap))
